package com.sanstech.iswinning

enum class ScoreType(val value: String) {
    REGULAR("r"),
    CURRENT("c"),
    HALF_TIME("ht"),
    EXTRA_TIME("et"),
    PENALTIES("pe"),
    PENALTY("p"),
    QUARTER_1("q1"),
    QUARTER_2("q2"),
    QUARTER_3("q3"),
    QUARTER_4("q4"),
    SET1("s1"),
    SET2("s2"),
    SET3("s3"),
    SET4("s4"),
    SET5("s5"),
    SET6("s6"),
    SET7("s7"),
    CORNER("co"),
    YELLOW_CARD("yc"),
    RED_CARD("rc"),
    INNING_1("i1"),
    INNING_2("i2"),
    INNING_3("i3"),
    INNING_4("i4"),
    INNING_5("i5"),
    INNING_6("i6"),
    INNING_7("i7"),
    INNING_8("i8"),
    INNING_9("i9"),
    EXTRA_INNING("ei"),
    SHOOTOUT("s"),
    CANCELLED("cc"),
    SET_GAME_SCORE("gs");
}